# Ordenando DataFrames

In [1]:
import pandas
import numpy

In [2]:
colunas_filmes = ['star_rating', 'title', 'content_rating', 'genre', 'duration', 'actors_list']

file = 'E:\\Udemy - Cursos\\Data Science\\Pacotes\\movies.csv'
filmes = pandas.read_csv(file, header = 0, names = colunas_filmes)
filmes.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [3]:
filmes.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [4]:
# Ordenando por título

filmes.title.sort_values().head()

542     (500) Days of Summer
5               12 Angry Men
201         12 Years a Slave
698                127 Hours
110    2001: A Space Odyssey
Name: title, dtype: object

In [5]:
# O retorno é uma Serie

A = filmes.title.sort_values()

type(A)

pandas.core.series.Series

In [6]:
A

542                   (500) Days of Summer
5                             12 Angry Men
201                       12 Years a Slave
698                              127 Hours
110                  2001: A Space Odyssey
910                                   2046
596                               21 Grams
624                              25th Hour
708                       28 Days Later...
60                                3 Idiots
225                                 3-Iron
570                                    300
555                           3:10 to Yuma
427           4 Months, 3 Weeks and 2 Days
824                                     42
597                                  50/50
203                                  8 1/2
170                       A Beautiful Mind
941                       A Bridge Too Far
571                           A Bronx Tale
266                      A Christmas Story
86                      A Clockwork Orange
716                         A Few Good Men
750                    A Fish Called Wanda
276                   A Fistful of Dollars
612                     A Hard Day's Night
883                  A History of Violence
869              A Nightmare on Elm Street
865                        A Perfect World
426                              A Prophet
                      ...
207       What Ever Happened to Baby Jane?
562            What's Eating Gilbert Grape
719                When Harry Met Sally...
649                      Where Eagles Dare
33                                Whiplash
669                Who Framed Roger Rabbit
219        Who's Afraid of Virginia Woolf?
127                      Wild Strawberries
497    Willy Wonka & the Chocolate Factory
270                        Wings of Desire
483                           Withnail & I
920                                Witness
65             Witness for the Prosecution
970                            Wonder Boys
518                         Wreck-It Ralph
954                                  X-Men
248             X-Men: Days of Future Past
532                     X-Men: First Class
871                                     X2
695                      Y Tu Mama Tambien
403                             Ying xiong
235                                Yip Man
96                                 Yojimbo
280                     Young Frankenstein
535                                  Zelig
955                       Zero Dark Thirty
677                                 Zodiac
615                             Zombieland
526                                   Zulu
864                                  [Rec]
Name: title, Length: 979, dtype: object

In [7]:
# Ordem Descendente

filmes.title.sort_values(ascending = False).head(10)

864                 [Rec]
526                  Zulu
615            Zombieland
677                Zodiac
955      Zero Dark Thirty
535                 Zelig
280    Young Frankenstein
96                Yojimbo
235               Yip Man
403            Ying xiong
Name: title, dtype: object

In [8]:
# Há outra forma de ordenar um DataFrame, desta forma, o retorno é um DataFrame

filmes.sort_values('title').head(10)

,star_rating,title,content_rating,genre,duration,actors_list
542,7.8,(500) Days of Summer,PG-13,Comedy,95,"[u'Zooey Deschanel', u'Joseph Gordon-Levitt', ..."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
201,8.1,12 Years a Slave,R,Biography,134,"[u'Chiwetel Ejiofor', u'Michael Kenneth Willia..."
698,7.6,127 Hours,R,Adventure,94,"[u'James Franco', u'Amber Tamblyn', u'Kate Mara']"
110,8.3,2001: A Space Odyssey,G,Mystery,160,"[u'Keir Dullea', u'Gary Lockwood', u'William S..."
910,7.5,2046,R,Drama,129,"[u'Tony Chiu Wai Leung', u'Ziyi Zhang', u'Faye..."
596,7.7,21 Grams,R,Crime,124,"[u'Sean Penn', u'Benicio Del Toro', u'Naomi Wa..."
624,7.7,25th Hour,R,Crime,135,"[u'Edward Norton', u'Barry Pepper', u'Philip S..."
708,7.6,28 Days Later...,R,Horror,113,"[u'Cillian Murphy', u'Naomie Harris', u'Christ..."
60,8.5,3 Idiots,PG-13,Comedy,170,"[u'Aamir Khan', u'Madhavan', u'Mona Singh']"

In [9]:
# Podemos também, ordenar de forma descendente

filmes.sort_values('title', ascending = False).head(10)

,star_rating,title,content_rating,genre,duration,actors_list
864,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."
526,7.8,Zulu,UNRATED,Drama,138,"[u'Stanley Baker', u'Jack Hawkins', u'Ulla Jac..."
615,7.7,Zombieland,R,Comedy,88,"[u'Jesse Eisenberg', u'Emma Stone', u'Woody Ha..."
677,7.7,Zodiac,R,Crime,157,"[u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
535,7.8,Zelig,PG,Comedy,79,"[u'Woody Allen', u'Mia Farrow', u'Patrick Horg..."
280,8.1,Young Frankenstein,PG,Comedy,106,"[u'Gene Wilder', u'Madeline Kahn', u'Marty Fel..."
96,8.4,Yojimbo,UNRATED,Action,110,"[u'Toshir\xf4 Mifune', u'Eijir\xf4 T\xf4no', u..."
235,8.1,Yip Man,R,Action,106,"[u'Donnie Yen', u'Simon Yam', u'Siu-Wong Fan']"
403,7.9,Ying xiong,PG-13,Action,99,"[u'Jet Li', u'Tony Chiu Wai Leung', u'Maggie C..."

In [10]:
# Apenas ordenar, não altera o DataFrame original

filmes.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [11]:
# Ordenando por classificação e duração

filmes.sort_values([ 'genre', 'duration']).head(10)

,star_rating,title,content_rating,genre,duration,actors_list
533,7.8,Run Lola Run,R,Action,80,"[u'Franka Potente', u'Moritz Bleibtreu', u'Her..."
633,7.7,The Warriors,R,Action,92,"[u'Michael Beck', u'James Remar', u'Dorsey Wri..."
455,7.9,Taken,PG-13,Action,93,"[u'Liam Neeson', u'Maggie Grace', u'Famke Jans..."
685,7.7,First Blood,R,Action,93,"[u'Sylvester Stallone', u'Brian Dennehy', u'Ri..."
744,7.6,Mad Max 2: The Road Warrior,R,Action,94,"[u'Mel Gibson', u'Bruce Spence', u'Michael Pre..."
619,7.7,Forbidden Planet,PASSED,Action,98,"[u'Walter Pidgeon', u'Anne Francis', u'Leslie ..."
276,8.1,A Fistful of Dollars,R,Action,99,"[u'Clint Eastwood', u'Gian Maria Volont\xe9', ..."
403,7.9,Ying xiong,PG-13,Action,99,"[u'Jet Li', u'Tony Chiu Wai Leung', u'Maggie C..."
552,7.8,Kung Fu Hustle,R,Action,99,"[u'Stephen Chow', u'Wah Yuen', u'Qiu Yuen']"
740,7.6,The Raid: Redemption,R,Action,101,"[u'Iko Uwais', u'Ananda George', u'Ray Sahetapy']"

# Filtrando um DataFrame

In [13]:
# Criando uma lista para saber os filmes com uma duração maior do que 150 minutos

boleanos = []

for length in filmes.duration:
    if length >= 150:
        boleanos.append(True)
    else:
           boleanos.append(False)

In [14]:
boleanos[: 20]

[False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False]

In [15]:
type(boleanos)

list

In [16]:
# Verificando o tamanho da lista

len(boleanos)

979

# É preciso converter a Lista em uma Serie para poder aplicar como filtro de DataFrame PANDAS

In [17]:
# Convertendo a Lista em Serie

duracao = pandas.Series(boleanos)

duracao.head(20)

0     False
1      True
2      True
3      True
4      True
5     False
6      True
7      True
8      True
9     False
10     True
11    False
12    False
13    False
14     True
15     True
16    False
17     True
18    False
19    False
dtype: bool

In [18]:
type(duracao)

pandas.core.series.Series

In [19]:
# É possível usar a notação de colchetes para indexar ou para aplicar filtros de series boleanos

print(filmes['title'] [: 15])

0                              The Shawshank Redemption
1                                         The Godfather
2                                The Godfather: Part II
3                                       The Dark Knight
4                                          Pulp Fiction
5                                          12 Angry Men
6                        The Good, the Bad and the Ugly
7         The Lord of the Rings: The Return of the King
8                                      Schindler's List
9                                            Fight Club
10    The Lord of the Rings: The Fellowship of the Ring
11                                            Inception
12       Star Wars: Episode V - The Empire Strikes Back
13                                         Forrest Gump
14                The Lord of the Rings: The Two Towers
Name: title, dtype: object

In [20]:
filmes[duracao]

,star_rating,title,content_rating,genre,duration,actors_list
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
14,8.8,The Lord of the Rings: The Two Towers,PG-13,Adventure,179,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort..."
15,8.7,Interstellar,PG-13,Adventure,169,"[u'Matthew McConaughey', u'Anne Hathaway', u'J..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
26,8.6,Once Upon a Time in the West,PG-13,Western,175,"[u'Henry Fonda', u'Charles Bronson', u'Claudia..."
36,8.6,Saving Private Ryan,R,Action,169,"[u'Tom Hanks', u'Matt Damon', u'Tom Sizemore']"
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."
42,8.5,The Pianist,R,Biography,150,"[u'Adrien Brody', u'Thomas Kretschmann', u'Fra..."
43,8.5,The Dark Knight Rises,PG-13,Action,165,"[u'Christian Bale', u'Tom Hardy', u'Anne Hatha..."
44,8.5,Gladiator,R,Action,155,"[u'Russell Crowe', u'Joaquin Phoenix', u'Conni..."
47,8.5,Taare Zameen Par,PG,Drama,165,"[u'Darsheel Safary', u'Aamir Khan', u'Tanay Ch..."
49,8.5,The Departed,R,Crime,151,"[u'Leonardo DiCaprio', u'Matt Damon', u'Jack N..."
50,8.5,Cinema Paradiso,R,Drama,155,"[u'Philippe Noiret', u'Enzo Cannavale', u'Anto..."
51,8.5,Apocalypse Now,R,Drama,153,"[u'Martin Sheen', u'Marlon Brando', u'Robert D..."
59,8.5,Django Unchained,R,Western,165,"[u'Jamie Foxx', u'Christoph Waltz', u'Leonardo..."
60,8.5,3 Idiots,PG-13,Comedy,170,"[u'Aamir Khan', u'Madhavan', u'Mona Singh']"
66,8.4,Munna Bhai M.B.B.S.,NOT RATED,Comedy,156,"[u'Sunil Dutt', u'Sanjay Dutt', u'Arshad Warsi']"
72,8.4,Rang De Basanti,NOT RATED,Drama,157,"[u'Aamir Khan', u'Soha Ali Khan', u'Siddharth']"
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
82,8.4,Braveheart,R,Action,177,"[u'Mel Gibson', u'Sophie Marceau', u'Patrick M..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
93,8.4,Dilwale Dulhania Le Jayenge,NOT RATED,Comedy,181,"[u'Shah Rukh Khan', u'Kajol', u'Amrish Puri']"
...,...,...,...,...,...,...
613,7.7,The Last Samurai,R,Action,154,"[u'Tom Cruise', u'Ken Watanabe', u'Billy Conno..."
620,7.7,Titanic,PG-13,Drama,194,"[u'Leonardo DiCaprio', u'Kate Winslet', u'Bill..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
649,7.7,Where Eagles Dare,NaN,Action,158,"[u'Richard Burton', u'Clint Eastwood', u'Mary ..."
659,7.7,Sophie's Choice,R,Drama,150,"[u'Meryl Streep', u'Kevin Kline', u'Peter MacN..."
665,7.7,Lolita,NOT RATED,Drama,152,"[u'James Mason', u'Shelley Winters', u'Sue Lyon']"
671,7.7,Grindhouse,R,Action,191,"[u'Kurt Russell', u'Rose McGowan', u'Danny Tre..."
677,7.7,Zodiac,R,Crime,157,"[u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M..."
678,7.7,Les Miserables,PG-13,Drama,158,"[u'Hugh Jackman', u'Russell Crowe', u'Anne Hat..."
684,7.7,The Big Blue,PG-13,Action,168,"[u'Jean-Marc Barr', u'Jean Reno', u'Rosanna Ar..."
707,7.6,Watchmen,R,Action,162,"[u'Jackie Earle Haley', u'Patrick Wilson', u'C..."
711,7.6,The Godfather: Part III,R,Crime,162,"[u'Al Pacino', u'Diane Keaton', u'Andy Garcia']"
720,7.6,Munich,R,Drama,164,"[u'Eric Bana', u'Daniel Craig', u'Marie-Jos\xe..."
727,7.6,Harry Potter and the Goblet of Fire,PG-13,Adventure,157,"[u'Daniel Radcliffe', u'Emma Watson', u'Rupert..."
730,7.6,West Side Story,UNRATED,Crime,152,"[u'Natalie Wood', u'George Chakiris', u'Richar..."
731,7.6,The Thin Red Line,R,Drama,170,"[u'Jim Caviezel', u'Sean Penn', u'Nick Nolte']"
734,7.6,The Last Temptation of Christ,R,Drama,164,"[u'Willem Dafoe', u'Harvey Keitel', u'Barbara ..."
755,7.6,"Lust, Caution",NC-17,Drama,157,"[u'Tony Chiu Wai Leung', u'Wei Tang', u'Joan C..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."
807,7.6,The Assassination of Jesse James by the Coward...,R,Biography,160,"[u'Brad Pitt', u'Casey Affleck', u'Sam Shepard']"
828,7.5,Gangs of New York,R,Crime,167,"[u'Leonardo DiCaprio', u'Cameron Diaz', u'Dani..."
836,7.5,Jackie Brown,R,Crime,154,"[u'Pam Grier', u'Samuel L. Jackson', u'Robert ..."
842,7.5,Cloud Atlas,R,Drama,172,"[u'Tom Hanks', u'Halle Berry', u'Hugh Grant']"
888,7.5,The Aviator,PG-13,Biography,170,"[u'Leonardo DiCaprio', u'Cate Blanchett', u'Ka..."
891,7.5,Harry Potter and the Half-Blood Prince,PG,Adventure,153,"[u'Daniel Radcliffe', u'Emma Watson', u'Rupert..."
909,7.5,Harry Potter and the Sorcerer's Stone,PG,Adventure,152,"[u'Daniel Radcliffe', u'Rupert Grint', u'Richa..."
941,7.4,A Bridge Too Far,PG,Drama,175,"[u'Sean Connery', u""Ryan O'Neal"", u'Michael Ca..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
964,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
968,7.4,The English Patient,R,Drama,162,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will..."

In [21]:
# É possível ainda, continuar a notação trazendo somente as colunas desejadas

filmes[duracao] [ ['title', 'duration', 'genre'] ]

                                                 title  duration      genre
1                                        The Godfather       175      Crime
2                               The Godfather: Part II       200      Crime
3                                      The Dark Knight       152     Action
4                                         Pulp Fiction       154      Crime
6                       The Good, the Bad and the Ugly       161    Western
7        The Lord of the Rings: The Return of the King       201  Adventure
8                                     Schindler's List       195  Biography
10   The Lord of the Rings: The Fellowship of the Ring       178  Adventure
14               The Lord of the Rings: The Two Towers       179  Adventure
15                                        Interstellar       169  Adventure
17                                       Seven Samurai       207      Drama
26                        Once Upon a Time in the West       175    Western
36                                 Saving Private Ryan       169     Action
40                                      The Green Mile       189      Crime
42                                         The Pianist       150  Biography
43                               The Dark Knight Rises       165     Action
44                                           Gladiator       155     Action
47                                    Taare Zameen Par       165      Drama
49                                        The Departed       151      Crime
50                                     Cinema Paradiso       155      Drama
51                                      Apocalypse Now       153      Drama
59                                    Django Unchained       165    Western
60                                            3 Idiots       170     Comedy
66                                 Munna Bhai M.B.B.S.       156     Comedy
72                                     Rang De Basanti       157      Drama
78                         Once Upon a Time in America       229      Crime
82                                          Braveheart       177     Action
85                                  Lawrence of Arabia       216  Adventure
89                                              Swades       189      Drama
93                         Dilwale Dulhania Le Jayenge       181     Comedy
..                                                 ...       ...        ...
613                                   The Last Samurai       154     Action
620                                            Titanic       194      Drama
630                                          Malcolm X       202  Biography
649                                  Where Eagles Dare       158     Action
659                                    Sophie's Choice       150      Drama
665                                             Lolita       152      Drama
671                                         Grindhouse       191     Action
677                                             Zodiac       157      Crime
678                                     Les Miserables       158      Drama
684                                       The Big Blue       168     Action
707                                           Watchmen       162     Action
711                            The Godfather: Part III       162      Crime
720                                             Munich       164      Drama
727                Harry Potter and the Goblet of Fire       157  Adventure
730                                    West Side Story       152      Crime
731                                  The Thin Red Line       170      Drama
734                      The Last Temptation of Christ       164      Drama
755                                      Lust, Caution       157      Drama
767                    It's a Mad, Mad, Mad, Mad World       205     Action
807  The Assassination of Jesse James by the Coward...       160  Biography
828                                  Gangs of New York       167      Crime
836                                       Jackie Brown       154      Crime
842                                        Cloud Atlas       172      Drama
888                                        The Aviator       170  Biography
891             Harry Potter and the Half-Blood Prince       153  Adventure
909              Harry Potter and the Sorcerer's Stone       152  Adventure
941                                   A Bridge Too Far       175      Drama
955                                   Zero Dark Thirty       157      Drama
964                                            Lincoln       150  Biography
968                                The English Patient       162      Drama

[129 rows x 3 columns]

# É possível simplificar o filtro conforme abaixo ou ainda escrevendo em List Comprehension

In [22]:
# Forma simplificada

A = filmes.duration >= 180

A.head(20)

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7      True
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
Name: duration, dtype: bool

In [23]:
filmes[A].head(16)

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
93,8.4,Dilwale Dulhania Le Jayenge,NOT RATED,Comedy,181,"[u'Shah Rukh Khan', u'Kajol', u'Amrish Puri']"
109,8.3,Dil Chahta Hai,NOT RATED,Comedy,183,"[u'Aamir Khan', u'Saif Ali Khan', u'Akshaye Kh..."
132,8.3,Judgment at Nuremberg,NOT RATED,Drama,186,"[u'Spencer Tracy', u'Burt Lancaster', u'Richar..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
143,8.2,The Wolf of Wall Street,R,Biography,180,"[u'Leonardo DiCaprio', u'Jonah Hill', u'Margot..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
166,8.2,The Deer Hunter,R,Drama,182,"[u'Robert De Niro', u'Christopher Walken', u'J..."
184,8.2,Fanny and Alexander,R,Drama,188,"[u'Bertil Guve', u'Pernilla Allwin', u'Kristin..."

In [24]:
# Escrevendo por List Comprehension

filmes[filmes.duration >= 180].head(20)

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
93,8.4,Dilwale Dulhania Le Jayenge,NOT RATED,Comedy,181,"[u'Shah Rukh Khan', u'Kajol', u'Amrish Puri']"
109,8.3,Dil Chahta Hai,NOT RATED,Comedy,183,"[u'Aamir Khan', u'Saif Ali Khan', u'Akshaye Kh..."
132,8.3,Judgment at Nuremberg,NOT RATED,Drama,186,"[u'Spencer Tracy', u'Burt Lancaster', u'Richar..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
143,8.2,The Wolf of Wall Street,R,Biography,180,"[u'Leonardo DiCaprio', u'Jonah Hill', u'Margot..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
166,8.2,The Deer Hunter,R,Drama,182,"[u'Robert De Niro', u'Christopher Walken', u'J..."
184,8.2,Fanny and Alexander,R,Drama,188,"[u'Bertil Guve', u'Pernilla Allwin', u'Kristin..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
220,8.1,Gandhi,PG,Biography,191,"[u'Ben Kingsley', u'John Gielgud', u'Candice B..."
245,8.1,Barry Lyndon,PG,Adventure,184,"[u""Ryan O'Neal"", u'Marisa Berenson', u'Patrick..."
316,8.0,JFK,R,Drama,189,"[u'Kevin Costner', u'Gary Oldman', u'Jack Lemm..."

In [25]:
# É possível também retornar outra série com a coluna que desejamos

genero_maior_200 = filmes[filmes.duration >= 200].genre

In [26]:
genero_maior_200

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object

In [27]:
type(genero_maior_200)

pandas.core.series.Series

In [28]:
# É possível utilizar a notação de colchetes para se fazer a mesma coisa

genero_maior_200 = filmes[filmes.duration >= 200] ['genre']

In [29]:
genero_maior_200

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object

In [30]:
# Porém, por uma boa prática, utilizamos sempre o método LOC que nada mais é do que definir uma condição e filtrar por labels 
# Veremos o ILOCcom mais detalhes 

filmes.loc[filmes.duration >= 200, 'genre']

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object